@startuml
'https://plantuml.com/class-diagram

class ArrayList {
    +void main
    ~Map<String, Integer> map
    +void readFile
    ~Map<String, Integer> map
    ~Scanner scan
    ~String string
    +void print
    ~Map<String, Integer> map
    ~String key
    ~int i
}


@enduml